name: regatta_weather

model-paths: [models]
seed-paths: [data]
test-paths: [tests]
clean-targets: ["target", "dbt_modules"]

profile: "dev"
# analysis-paths: [directorypath]
# macro-paths: [directorypath]
# snapshot-paths: [directorypath]
# docs-paths: [directorypath]
# asset-paths: [directorypath]