interactive:
  target: dv
  outputs:
    dv:
      connect_timeout: 10
      database: Regatta_weather
      host: hostname
      keepalives_idle: 0
      password: postgres
      port: 5432
      retries: 1
      schema: regatta_network_raw
      type: postgres
      user: postgres

